version: '3'

services:
  placehd:
    image: placehcoin/core:latest
    build: .
    restart: always
    volumes:
       - ./.appdata/.placeh:/home/placeh/.placeh
    command: [
      "placehd",
      "-printtoconsole",
      "-rpcuser=root",
      "-rpcpassword=x",
      "-rpcallowip=0.0.0.0/0",
      "-rpcport=2300",
      "-rpcbind=0.0.0.0",
      "-server",
      "-listen",
      "-addnode=174.138.55.214",
    ]
    ports:
      - "2300:2300"
    expose:
      - 2300
    networks:
      default:
        aliases:
          - placehd.internal
