name: Docker CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  alpine-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get snapshot hash, version & branch
        id: snapshot
        run: |
          echo "::set-env name=GIT_HASH::$(git rev-parse --short=7 "$GITHUB_SHA")"
          echo "::set-env name=LAST_TAG::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "::set-env name=COMMITS_AHEAD::$(git rev-list $(git describe --tags $(git rev-list --tags --max-count=1)).. --count)"
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//./g')"
          echo "::set-env name=TAGS::$(if [ "${{ github.event_name }}" == "push" ] && [ "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" == "master" ]; then echo "latest,$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; elif [ "${{ github.event_name }}" == "pull_request" ]; then echo ""; else echo "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; fi)"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@508d4ee
        with:
          dockerfile: dev.Dockerfile
          name: veriblock/phl
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          tags: "phl-${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }}"
      - name: Show Tags
        run: |
          echo "Successfully pushed the following tags:"
          echo "----"
          echo "pop-${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }}"
          echo "----"

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: ["Release", "Debug"]
    steps:
      - uses: actions/checkout@v1
      - name: Get snapshot hash, version & branch
        id: snapshot
        run: |
          echo "::set-env name=GIT_HASH::$(git rev-parse --short=7 "$GITHUB_SHA")"
          echo "::set-env name=LAST_TAG::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "::set-env name=COMMITS_AHEAD::$(git rev-list $(git describe --tags $(git rev-list --tags --max-count=1)).. --count)"
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//./g')"
          echo "::set-env name=TAGS::$(if [ "${{ github.event_name }}" == "push" ] && [ "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" == "master" ]; then echo "latest,$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; elif [ "${{ github.event_name }}" == "pull_request" ]; then echo ""; else echo "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; fi)"
      - name: Publish to Registry
        env:
          BUILD_TYPE: ${{ matrix.build }}
        uses: elgohr/Publish-Docker-Github-Action@508d4ee
        with:
          name: veriblock/phl
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          dockerfile: ubuntu-dev.Dockerfile
          tags: "phl-ubuntu-${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }}-${{ matrix.build }}"
      - name: Show Tags
        run: |
          echo "Successfully pushed the following tags:"
          echo "----"
          echo "pop-ubuntu-${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }}-${{ matrix.build }}"
          echo "----"